yarn download:tidb:zh
yarn download:tidb:zh --ref release-8.3
yarn download:tidb:zh --ref release-8.2
yarn download:tidb:zh --ref release-8.1
yarn download:tidb:zh --ref release-8.0
yarn download:tidb:zh --ref release-7.6
yarn download:tidb:zh --ref release-7.5
yarn download:tidb:zh --ref release-7.4
yarn download:tidb:zh --ref release-7.3
yarn download:tidb:zh --ref release-7.2
yarn download:tidb:zh --ref release-7.1
yarn download:tidb:zh --ref release-7.0
yarn download:tidb:zh --ref release-6.6
yarn download:tidb:zh --ref release-6.5
yarn download:tidb:zh --ref release-6.4
yarn download:tidb:zh --ref release-6.3
yarn download:tidb:zh --ref release-6.2
yarn download:tidb:zh --ref release-6.1
yarn download:tidb:zh --ref release-6.0
yarn download:tidb:zh --ref release-5.4
yarn download:tidb:zh --ref release-5.3
yarn download:tidb:zh --ref release-5.2
yarn download:tidb:zh --ref release-5.1
yarn download:tidb:zh --ref release-5.0
yarn download:tidb:zh --ref release-4.0
yarn download:tidb:zh --ref release-3.1
yarn download:tidb:zh --ref release-3.0
yarn download:tidb:zh --ref release-2.1
