yarn download:tidb-operator en main
yarn download:tidb-operator en release-2.0
yarn download:tidb-operator en release-1.6
yarn download:tidb-operator en release-1.5
yarn download:tidb-operator en release-1.4
yarn download:tidb-operator en release-1.3
yarn download:tidb-operator en release-1.2
yarn download:tidb-operator en release-1.1
yarn download:tidb-operator en release-1.0
